
events {}

http {

server {

listen 80;

location / {
root /usr/share/nginx/html;
index index.html;
}

location /auth/ {
proxy_pass http://auth:8001/;
}

location /vault/ {
proxy_pass http://vault:8002/;
}

}

}
