services:

  auth:
    build: ./auth-service
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy

  vault:
    build: ./vault-service
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: vault
      POSTGRES_DB: vaultdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vault -d vaultdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

  gateway:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - auth
      - vault
